name: Automated Maintenance Task

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes for testing purposes

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main  # Garante que o workflow execute na branch main

      - name: Switch to maintenance branch
        run: |
          git checkout -b maintenance origin/maintenance || git checkout maintenance

      - name: Repository maintenance check
        run: |
          echo "## Maintenance update on: $(date '+%Y-%m-%d %H:%M:%S')" >> README.md

      - name: Configure git settings
        run: |
          git config user.name "felipemacedo1"
          git config user.email "felipealexandrej@gmail.com"

      - name: Commit and Push changes to maintenance branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add README.md
          git commit -m "Automated maintenance update"
          git push https://$GITHUB_TOKEN@github.com/BliShem/CryptoTool.git maintenance
