name: Automated Maintenance Task

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Switch to maintenance branch
        run: |
          git checkout -b maintenance origin/maintenance || git checkout maintenance

      - name: Repository maintenance check
        run: |
          echo "## Maintenance update on: $(date '+%Y-%m-%d %H:%M:%S')" >> README.md

      - name: Configure git settings
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Commit and Push changes to maintenance branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add README.md
          git commit -m "Automated maintenance update"
          git push https://$GITHUB_TOKEN@github.com/shem-org/CryptoTool.git maintenance
