name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read  # Permite que o SonarCloud adicione resultados da análise aos PRs

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Verificar a versão Go instalada
      - name: Check Go version
        run: go version  # Verifica a versão Go no runner

      # 3. Configurar o Go com a versão 1.22.5
      - name: Set up Go 1.22.5
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
          check-latest: true  # Força a instalação da versão mais recente 1.22.5

      # 4. Executar testes e gerar o relatório de cobertura
      - name: Run tests and generate coverage
        run: |
          go test -coverprofile=coverage.out ./...
          ls -l coverage.out  # Lista o arquivo de cobertura para garantir que foi gerado

      # 5. Upload do arquivo de cobertura como artefato para depuração
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out

      # 6. Executar análise do SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SHEM }}  # O token configurado nos segredos do GitHub
        with:
          args: >
            -Dsonar.projectKey=shem-org_CryptoTool
            -Dsonar.organization=shem-org
            -Dsonar.go.coverage.reportPaths=coverage.out
            -Dsonar.verbose=true

      # 7. Baixar logs detalhados para inspeção (opcional)
      - name: Download SonarCloud Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: sonarcloud-logs
          path: .scannerwork
